[[Qt65Compat]]
arch = "aarch64"
git-tree-sha1 = "0a98dbf6d71bda538398650632671dd6ad463a03"
os = "macos"

    [[Qt65Compat.download]]
    sha256 = "92e71f98607dfa031077236c9ea9e04d5515c6cef2d08272d009465858ab352c"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.aarch64-apple-darwin.tar.gz"
[[Qt65Compat]]
arch = "x86_64"
git-tree-sha1 = "6475ee82211c5e6504aa210f31b6c905ddb96956"
os = "macos"

    [[Qt65Compat.download]]
    sha256 = "def1f7fe798b4ceebc4e5d92c044b5d62b7bd72e43fe3445916d954ad1c154a5"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.x86_64-apple-darwin.tar.gz"
[[Qt65Compat]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3914856ee678047e099e4982cfffff771b3ff65f"
os = "windows"

    [[Qt65Compat.download]]
    sha256 = "9635b9b0faf4c7e74e6b07d139e9db4cf34cccf88ce3d01e0f6a50adc420ce11"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt65Compat]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30d03a9eadef58fe5dfa7f98cf76fde3b667ad19"
os = "windows"

    [[Qt65Compat.download]]
    sha256 = "654415fb5a26b4a81288e0540343d614f76a543341ae26c0079707a4a41a7112"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt65Compat]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95873deb5089609ce5c2b168238e8de8d020926d"
libc = "glibc"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "83a6ca8308558bf1af9cd71a938a7c2bdbadc5b0bf985fb68b35be8519974e4f"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt65Compat]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30291de54587f0c6b2370468fa5546de4a677ecc"
libc = "musl"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "cecaf1c898260ed2128a3cf56891ab2dc351c5f1c10e9e3516ae01db1039410f"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt65Compat]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a0dfd07d0001502d52fc35b580bf2e138fe93d3"
libc = "glibc"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "cd3e8b5bcd293cfa0642059a6a500daf2edd8d945d0077c4503c30492304ee25"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt65Compat]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad6ffdf4b1bc077471431295ac9e5885c5c564c9"
libc = "musl"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "fa192196bc6581d258c7eb6386137d7b5098e55b9d8f3d3aabc45ff971fe98b5"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt65Compat]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2324743be058a86fa6ad91a98b4189f67d19d86"
libc = "glibc"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "f3cad2978c1224ca20c5ce3369a126e6efda8eecd3560c9f5435c260896ab13c"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt65Compat]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31598ebca83f0065f3521c5cea67e9ced89b269c"
libc = "musl"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "943e1132411804b0c8e870bc184eb7cfc54a6a56bb33728e04fff1175ecf8977"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.i686-linux-musl-cxx11.tar.gz"
[[Qt65Compat]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bc121786fa2c35b56c82b81df8c10f1f9fce6ed"
libc = "glibc"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "a00e1c6b638497afdf9979e8dd382ed2abdfc31421fd1900eba1ae456710882f"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt65Compat]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9ef5846372ce9083795057ff747cdb64923b622"
libc = "glibc"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "b6faf40c3ec10b04e753a2451121bc330e5ebe73436798cc06078d02eb2b24b7"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt65Compat]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df9e3ba16d51315caa573a3efa917999f77f37ed"
libc = "musl"
os = "linux"

    [[Qt65Compat.download]]
    sha256 = "309fc89c9969348f91e2cff4b2783ae96ad7520f707706c7af2f7d9bab285441"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[Qt65Compat]]
arch = "x86_64"
git-tree-sha1 = "e0f1b9c3441820fcbcae3a844f2dcd991e1927b2"
os = "freebsd"

    [[Qt65Compat.download]]
    sha256 = "1e9e4e9b0ab1c43f17fe5a778118820e2358990897dec53cfd90466a42512948"
    url = "https://github.com/JuliaBinaryWrappers/Qt65Compat_jll.jl/releases/download/Qt65Compat-v6.10.2+0/Qt65Compat.v6.10.2.x86_64-unknown-freebsd.tar.gz"
